# =============================================================================
# Daily Zomato batch pipeline
# =============================================================================
# reload_raw -> dbt_build_core -> dbt_snapshot -> enrich_reviews -> dbt_build_ai -> dbt_docs_generate
#
# Why the build is split in two:
#
#   dbt_build_core  builds Silver and Gold with `--exclude tag:ai`. It must run
#                   BEFORE enrichment, because mart_review_insights reads
#                   ZOMATO.AI.REVIEW_ENRICHED — a table that does not exist until
#                   the AI job has run at least once. Excluding by tag is what
#                   lets a brand-new warehouse bootstrap itself in one pass.
#
#   enrich_reviews  the LLM step. Idempotent and sample-capped, so a retry or a
#                   re-run never pays OpenAI twice for the same review.
#
#   dbt_build_ai    `--select tag:ai` — now that REVIEW_ENRICHED exists, build
#                   mart_review_insights and run its tests.
#
# Credentials never appear in this file. docker-compose injects SNOWFLAKE_* and
# OPENAI_API_KEY as environment variables (dbt's profiles.yml reads them through
# env_var()), and the COPY task uses the AIRFLOW_CONN_SNOWFLAKE_DEFAULT
# connection definition.
# =============================================================================
from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.providers.standard.operators.bash import BashOperator

DBT = "/opt/airflow/dbt_venv/bin/dbt"
DBT_PROJECT = "/opt/airflow/dbt/zomato"
DBT_FLAGS = f"--project-dir {DBT_PROJECT} --profiles-dir {DBT_PROJECT}"
ENRICH_SCRIPT = "/opt/airflow/ai/enrich_reviews.py"

# -----------------------------------------------------------------------------
# Bronze load
# -----------------------------------------------------------------------------
# The error mode is chosen by who owns the defect, and it is deliberately NOT the
# same for every table:
#
#   dimensions  ON_ERROR = 'CONTINUE'
#       restaurants / users / food / menu are "real world" exports. A rating that
#       will not parse is Tuesday, not an incident: skip the row, keep the other
#       148,540, and inspect the rejects with TABLE(VALIDATE(...)).
#
#   facts       ON_ERROR = 'ABORT_STATEMENT'
#       orders / order_items / reviews are written by data/generator/. A row that
#       will not parse is a bug in YOUR code, and a silently skipped fact row
#       makes every downstream number quietly wrong — which is exactly the failure
#       the reconciliation test in zomato/tests/ exists to catch.
#
# This matches snowflake/05_copy_into.sql on purpose. The scheduled job and the
# manual script must not disagree about how strict the pipeline is.
#
# Re-running is safe and costs nothing: Snowflake remembers which files it has
# already loaded, so a second run processes zero files unless you set FORCE.
COPY_RAW = [
    "USE WAREHOUSE ZOMATO_WH",
    # dimensions — messy source data: tolerate the row and report it
    "COPY INTO ZOMATO.RAW.restaurants FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/restaurants/ ON_ERROR = 'CONTINUE'",
    "COPY INTO ZOMATO.RAW.users       FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/users/       ON_ERROR = 'CONTINUE'",
    "COPY INTO ZOMATO.RAW.food        FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/food/        ON_ERROR = 'CONTINUE'",
    "COPY INTO ZOMATO.RAW.menu        FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/menu/        ON_ERROR = 'CONTINUE'",
    # facts — generated by our own code: stay strict so the counts are exact
    "COPY INTO ZOMATO.RAW.orders      FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/orders/      ON_ERROR = 'ABORT_STATEMENT'",
    "COPY INTO ZOMATO.RAW.order_items FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/order_items/ ON_ERROR = 'ABORT_STATEMENT'",
    "COPY INTO ZOMATO.RAW.reviews     FROM @ZOMATO.RAW.ZOMATO_RAW_STAGE/reviews/     ON_ERROR = 'ABORT_STATEMENT'",
]

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "email_on_failure": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="zomato_batch",
    description="S3 -> Snowflake -> dbt -> LLM enrichment -> dbt AI mart, daily.",
    start_date=datetime(2024, 1, 1),
    schedule="@daily",
    catchup=False,
    max_active_runs=1,          # the incremental MERGEs are not safe to run concurrently
    tags=["zomato", "snowflake", "dbt", "ai"],
    default_args=default_args,
    doc_md=__doc__,
) as dag:

    # -------------------------------------------------------------------------
    # 1. S3 -> Snowflake RAW
    # -------------------------------------------------------------------------
    reload_raw = SQLExecuteQueryOperator(
        task_id="reload_raw",
        conn_id="snowflake_default",
        sql=COPY_RAW,
        split_statements=True,
        autocommit=True,
        execution_timeout=timedelta(hours=2),
    )

    # -------------------------------------------------------------------------
    # 2. Silver + Gold — everything except the AI-tagged models and the snapshot.
    #
    #    `--exclude tag:ai` is load-bearing. mart_review_insights reads a table
    #    that does not exist until enrich_reviews has run, and the SAME is true of
    #    the generic tests declared on the AI *source* — a source test is its own
    #    node with its own tags. All of them carry `ai`.
    #
    #    `--exclude resource_type:snapshot` is here because `dbt build` DOES run
    #    snapshots: it builds models, tests, snapshots and seeds in DAG order.
    #    Without the exclusion the snapshot would run twice per scheduled run —
    #    once here, once in dbt_snapshot. Excluding it gives the SCD2 step exactly
    #    one owner, which is the point of task 3 existing at all.
    # -------------------------------------------------------------------------
    dbt_build_core = BashOperator(
        task_id="dbt_build_core",
        bash_command=f"{DBT} build --exclude tag:ai --exclude resource_type:snapshot {DBT_FLAGS}",
        execution_timeout=timedelta(hours=4),
        append_env=True,
    )

    # -------------------------------------------------------------------------
    # 3. SCD2 snapshot of the restaurant dimension.
    #
    #    Given its own task even though `dbt build` would happily run it, so that
    #    the snapshot has an independent timeout, its own retry, and a visible
    #    green/red box in the UI — and so a snapshot failure cannot be hidden
    #    inside a four-hour model build. Task 2 excludes snapshots, so this task
    #    is the only writer.
    # -------------------------------------------------------------------------
    dbt_snapshot = BashOperator(
        task_id="dbt_snapshot",
        bash_command=f"{DBT} snapshot {DBT_FLAGS}",
        execution_timeout=timedelta(hours=1),
        append_env=True,
    )

    # -------------------------------------------------------------------------
    # 4. LLM enrichment (safe to fail softly — un-enriched rows stay pending)
    # -------------------------------------------------------------------------
    enrich_reviews = BashOperator(
        task_id="enrich_reviews",
        bash_command=f"python {ENRICH_SCRIPT}",
        execution_timeout=timedelta(hours=2),
        append_env=True,
    )

    # -------------------------------------------------------------------------
    # 5. The AI-tagged mart, now that its source table exists
    # -------------------------------------------------------------------------
    dbt_build_ai = BashOperator(
        task_id="dbt_build_ai",
        bash_command=f"{DBT} build --select tag:ai {DBT_FLAGS}",
        execution_timeout=timedelta(hours=1),
        append_env=True,
    )

    # -------------------------------------------------------------------------
    # 6. Regenerate the docs site so `dbt docs serve` is always current.
    #    Writes into the mounted zomato/target/ directory.
    # -------------------------------------------------------------------------
    dbt_docs_generate = BashOperator(
        task_id="dbt_docs_generate",
        bash_command=f"{DBT} docs generate {DBT_FLAGS}",
        execution_timeout=timedelta(minutes=30),
        append_env=True,
    )

    reload_raw >> dbt_build_core >> dbt_snapshot >> enrich_reviews >> dbt_build_ai >> dbt_docs_generate
